[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Hasklug Nerd Font"
style = "Medium"
[font.bold]
style = "SemiBold"
[font.italic]
style = "Medium Italic"
[font.bold_italic]
style = "SemiBold Italic"

[general]
import = [ "~/.config/alacritty/themes/themes/solarized_dark.toml" ]
